name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Setup config (using SAMPLE-config.py as config.py) - LINUX
      run: python .github/workflows/verify_result.py -c ${{ matrix.config }}
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
