name: "Regression Test - Tracking and Privacy (Pagexray) Test"
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      if: ${{ success() }}
    - name: Test Tracking and Privacy
      run: |
        docker run --rm -v /home/runner/work/webperf_core/webperf_core/:/sitespeed.io sitespeedio/sitespeed.io:latest --shm-size=1g -b chrome --plugins.remove screenshot --browsertime.chrome.collectPerfLog --browsertime.chrome.includeResponseBodies "all" --html.fetchHARFiles true --firstParty --utc true --xvfb --browsertime.chrome.args ignore-certificate-errors https://webperf.se/
      if: ${{ success() }}
    - name: Test Directory
      run: |
        echo "# current folder"
        ls
      if: ${{ always() }}
    - name: Test Directory
      run: |
        echo "# sitespeed"
        ls sitespeed
      if: ${{ always() }}
