name: "Test"
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      if: ${{ success() }}
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
      if: ${{ success() }}
    - name: Setup config (using SAMPLE-config.py as config.py)
      run: python .github/workflows/verify_result.py -c
      if: ${{ success() }}
    - name: Download IP2LOCATION DB (Using repository secret)
      shell: bash
      env:
        IP2LOCATION_DOWNLOAD_URL: ${{ secrets.IP2LOCATION_DOWNLOAD_URL }}
      run: wget -q -O - $IP2LOCATION_DOWNLOAD_URL | tar -xvzf - -C data
      if: ${{ success() }}
    - name: Setup Node.js (v1 version 14.x)
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      if: ${{ success() }}
    - name: Setup Google Chrome browser (ONLY used for Sitespeed)
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
      if: ${{ success() }}
    - name: Setup GeckoDriver (Used for Selenium)
      run: wget -q -O - https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz | tar -xvzf -
      if: ${{ success() }}
    - name: Setup Sitespeed.io npm package (ONLY used for Sitespeed)
      run: npm install -g sitespeed.io
      if: ${{ success() }}
    - name: Download Ads database (BlockListProject)
      run: |
        wget -q -O data/blocklistproject-ads-nl.txt https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt
        echo "# data"
        ls data
      if: ${{ success() }}
    - name: Download Tracking database (BlockListProject)
      run: |
        wget -q -O data/blocklistproject-tracking-nl.txt https://blocklistproject.github.io/Lists/alt-version/tracking-nl.txt
        echo "# data"
        ls data
      if: ${{ success() }}
    - name: Download Services database (disconnect)
      run: |
        wget -q -O data/disconnect-services.json https://raw.githubusercontent.com/disconnectme/disconnect-tracking-protection/master/services.json
        echo "# data"
        ls data
      if: ${{ success() }}
    # - name: Test Tracking and Privacy - https://www.kodagent.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.kodagent.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://nimbleinitiatives.com/
    #   run: |
    #     python default.py -t 23 -r -u https://nimbleinitiatives.com/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    - name: Test Tracking and Privacy - https://sorundanet.se/hem/index.html
      run: |
        python default.py -t 23 -r -u https://sorundanet.se/hem/index.html -o .github/workflows/testresult-23.json
        python .github/workflows/verify_result.py -t 23
      if: ${{ always() }}
    - name: SHOW - https://sorundanet.se/hem/index.html
      run: |
        echo "# pages"
        ls results/pages/
        echo "# sorundanet_se"
        ls results/pages/sorundanet_se/
        echo "# hem"
        ls results/pages/sorundanet_se/hem/
        echo "# index.html"
        ls results/pages/sorundanet_se/hem/index.html/
      if: ${{ always() }}
    - name: Test Tracking and Privacy - https://lokalapartier.se/home/index.html
      run: |
        python default.py -t 23 -r -u https://lokalapartier.se/home/index.html -o .github/workflows/testresult-23.json
        python .github/workflows/verify_result.py -t 23
      if: ${{ always() }}
    - name: SHOW - https://lokalapartier.se/home/index.html
      run: |
        echo "# pages"
        ls results/pages/
        echo "# lokalapartier_se"
        ls results/pages/lokalapartier_se/
        echo "# home"
        ls results/pages/lokalapartier_se/home/
        echo "# index.html"
        ls results/pages/lokalapartier_se/home/index.html/
      if: ${{ always() }}
    - name: Test Tracking and Privacy - https://polisen.se/aktuellt/polisens-nyheter/?lpfm.loc=Stockholms%20l%C3%A4n
      run: |
        python default.py -t 23 -r -u https://polisen.se/aktuellt/polisens-nyheter/?lpfm.loc=Stockholms%20l%C3%A4n -o .github/workflows/testresult-23.json
        python .github/workflows/verify_result.py -t 23
      if: ${{ always() }}
    - name: SHOW - https://polisen.se/aktuellt/polisens-nyheter/?lpfm.loc=Stockholms%20l%C3%A4n
      run: |
        echo "# pages"
        ls results/pages/
        echo "# polisen_se"
        ls results/pages/polisen_se/
        echo "# aktuellt"
        ls results/pages/polisen_se/aktuellt/
        echo "# polisens-nyheter"
        ls results/pages/polisen_se/aktuellt/polisens-nyheter/
      if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.textamig.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.textamig.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://polisen.se/
    #   run: |
    #     python default.py -t 23 -r -u https://polisen.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.happiness.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.happiness.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.mucf.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.mucf.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://axesslab.com/
    #   run: |
    #     python default.py -t 23 -r -u https://axesslab.com/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.itiden.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.itiden.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.municipio.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.municipio.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://polismuseet.se/
    #   run: |
    #     python default.py -t 23 -r -u https://polismuseet.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.oru.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.oru.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.mprt.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.mprt.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.hallakonsument.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.hallakonsument.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://tidningensvenskpolis.se/
    #   run: |
    #     python default.py -t 23 -r -u https://tidningensvenskpolis.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.umu.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.umu.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://whitespace.se/
    #   run: |
    #     python default.py -t 23 -r -u https://whitespace.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.transpatientforening.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.transpatientforening.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
    # - name: Test Tracking and Privacy - https://www.vallentuna.se/
    #   run: |
    #     python default.py -t 23 -r -u https://www.vallentuna.se/ -o .github/workflows/testresult-23.json
    #     python .github/workflows/verify_result.py -t 23
    #   if: ${{ always() }}
