name: "Regression Test - Sitespeed.io - Browsertime.har fields and structure"
on:
  workflow_dispatch:
  push:
    paths:
      - '**verify_result.py'
      - '**regression-test-sitespeed-browsertime-har.yml'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest]
                browser: ['firefox', 'chrome']
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
    - name: Setup QEMU # used to allow multiplatform docker builds
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx # used to allow multiplatform docker builds
      uses: docker/setup-buildx-action@v3
    - name: Testing sitespeed.io:s browsertime.har output using ${{ matrix.browser }}
      if: always()
      run: |
        command="docker run --rm -v $(pwd):/sitespeed.io sitespeedio/sitespeed.io:35.7.0 -b ${{ matrix.browser }} -n 1 --chrome.includeResponseBodies html --firefox.includeResponseBodies html https://webperf.se"
        echo "$command"
        testresult=$($command)
        echo "$testresult"
        path=$(echo "$testresult" | grep -o "/sitespeed.io/.*")
        if [ -n result ]; then
          har_file=$(find $(pwd) -name "browsertime.har")
          if [ -f "$har_file" ]; then
            echo "Found browsertime.har at $har_file"
            python .github/workflows/verify_result.py --browsertime $har_file
          else
            echo "Error: browsertime.har not found in $path"
            exit 1
          fi
        else
          echo "Error: No path found starting with /sitespeed.io/"
          exit 1
        fi
