name: "Regression Test - Docker Image"
on:
  workflow_dispatch:
  push:
    paths:
      - '**regression-test-docker-image.yml'
      - 'software-full.json'
      - 'software-sources.json'
      - 'package.json'
      - 'Dockerfile'
      - 'update_software.py'
      - 'SAMPLE-software-rules.json'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          os: [ubuntu-latest]
          config: ['REVIEW_SHOW_IMPROVEMENTS_ONLY=True']
          version: [9]
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t "webperf-runner:latest" .
    - name: Check if we have correct python version
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest python --version
    - name: Check if webperf_core help command works
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest python default.py -h
    - name: Check if webperf_core can run Standard files Test
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest python default.py -t ${{ matrix.version }} -r -i sites.json -o .github/workflows/testresult-${{ matrix.version }}.json
    - name: Check if webperf_core returned correct data output in Standard files Regression Test
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest python .github/workflows/verify_result.py -t ${{ matrix.version }}
  