name: "Test"
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      if: ${{ success() }}
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
      if: ${{ success() }}
    - name: Setup Node.js (v1 version 14.x)
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Setup Google Chrome browser (ONLY used for Sitespeed)
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version      
      if: ${{ success() }}
    - name: Setup Sitespeed.io npm package (ONLY used for Sitespeed)
      run: npm install -g sitespeed.io
      if: ${{ success() }}
    # - name: Setup config (using SAMPLE-config.py as config.py)
    #   run: python .github/workflows/verify_result.py -c
    #   if: ${{ success() }}
    # - name: Test Performance (Sitespeed.io)
    #   run: sitespeed.io --rm --shm-size=1g -b chrome --plugins.remove screenshot --browsertime.chrome.includeResponseBodies --summary-detail true --outputFolder results --firstParty --utc --xvfb --browsertime.videoParams.createFilmstrip false --browsertime.chrome.args ignore-certificate-errors -n 2 https://webperf.se/
    #   if: ${{ always() }}
    - name: SiteSpeed Test 1
      run: |
        sitespeed.io -b chrome --plugins.remove screenshot --browsertime.chrome.includeResponseBodies "all" --html.fetchHARFiles true --summary-detail true --logToFile true --outputFolder results --firstParty --utc true --xvfb --browsertime.videoParams.createFilmstrip false --browsertime.chrome.args ignore-certificate-errors --html.logDownloadLink true -n 1 https://webperf.se/
        echo '# root'
        ls /home/runner/work/webperf_core/webperf_core
        echo '# root / data'
        ls /home/runner/work/webperf_core/webperf_core/data
        echo '# root / results'
        ls /home/runner/work/webperf_core/webperf_core/results
        echo '# root / results / logs'
        ls /home/runner/work/webperf_core/webperf_core/results/logs
        echo '# root / results / pages'
        ls /home/runner/work/webperf_core/webperf_core/results/pages
        echo '# root / results / pages / webperf_se'
        ls /home/runner/work/webperf_core/webperf_core/results/pages/webperf_se
        echo '# root / results / pages / webperf_se / data'
        ls /home/runner/work/webperf_core/webperf_core/results/pages/webperf_se/data
      if: ${{ always() }}
    - name: SiteSpeed Test 1 - HAR
      run: cat /home/runner/work/webperf_core/webperf_core/results/pages/webperf_se/data/browsertime.har
      if: ${{ always() }}
    - name: SiteSpeed Test 1 - Trace-1
      run: |
        tar -xvzf /home/runner/work/webperf_core/webperf_core/results/pages/webperf_se/data/trace-1.json.gz -C trace-1
        echo '# cat root / results / pages / webperf_se / data / trace-1'
        ls /home/runner/work/webperf_core/webperf_core/results/pages/webperf_se/data/trace-1
      if: ${{ always() }}
    - name: SiteSpeed Test 2
      run: |
        sitespeed.io -b chrome --plugins.remove screenshot --browsertime.chrome.includeResponseBodies "all" --html.fetchHARFiles true --summary-detail true --logToFile true --outputFolder results2 --firstParty --utc true --xvfb --browsertime.videoParams.createFilmstrip false --browsertime.chrome.args ignore-certificate-errors --html.logDownloadLink true -n 1 https://polisen.se/aktuellt/polisens-nyheter/
        echo '# root / results2'
        ls /home/runner/work/webperf_core/webperf_core/results2
        echo '# root / results2 / logs'
        ls /home/runner/work/webperf_core/webperf_core/results2/logs
        echo '# root / results2 / pages'
        ls /home/runner/work/webperf_core/webperf_core/results2/pages
        echo '# root / results2 / pages / polisen_se'
        ls /home/runner/work/webperf_core/webperf_core/results2/pages/polisen_se
        echo '# root / results2 / pages / polisen_se / data'
        ls /home/runner/work/webperf_core/webperf_core/results2/pages/polisen_se/data
      if: ${{ always() }}
    - name: SiteSpeed Test 3
      run: |
        sitespeed.io -b chrome --name zelda --groupAlias link --plugins.remove screenshot --browsertime.chrome.includeResponseBodies "all" --html.fetchHARFiles true --summary-detail true --logToFile true --outputFolder results3 --firstParty --utc true --xvfb --browsertime.videoParams.createFilmstrip false --browsertime.chrome.args ignore-certificate-errors --html.logDownloadLink true -n 1 https://st.nu/
        echo '# root / results3'
        ls /home/runner/work/webperf_core/webperf_core/results3
        echo '# root / results3 / logs'
        ls /home/runner/work/webperf_core/webperf_core/results3/logs
        echo '# root / results3 / pages'
        ls /home/runner/work/webperf_core/webperf_core/results3/pages
        echo '# root / results3 / pages / st_nu'
        ls /home/runner/work/webperf_core/webperf_core/results3/pages/st_nu
        echo '# root / results3 / pages / st_nu / data'
        ls /home/runner/work/webperf_core/webperf_core/results3/pages/st_nu/data
      if: ${{ always() }}
