name: "Regression Test - Docker Image"
on:
  workflow_dispatch:
  push:
    paths:
      - '**regression-test-docker-image.yml'
      - 'software-full.json'
      - 'software-sources.json'
      - 'package.json'
      - 'Dockerfile'
      - 'update_software.py'
      - 'SAMPLE-software-rules.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t "webperf-runner:latest" .
    - name: Test running Webperf_core Docker image
      if: always()
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest python3 --version
    - name: Test running Webperf_core Docker image
      if: always()
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest python --version
    - name: Test running Webperf_core Docker image
      if: always()
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest
    - name: Test running Webperf_core Docker image
      if: always()
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest python3 default.py -h
    - name: Test running Webperf_core Docker image
      if: always()
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest python default.py -h
    - name: Test running Webperf_core Docker image
      if: always()
      run: docker run -v "$(pwd):/webperf-runner" webperf-runner:latest
