name: "Regression Test - Integrity & Security (Webbkoll) Test"
on:
  push:
    paths-ignore:
      - '**.md'
env:
  TEST_TO_RUN: 20
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      if: ${{ success() }}
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
      if: ${{ success() }}
    - if: ${{ matrix.os == 'ubuntu-latest' && success()  }}
      name: Setup config (using SAMPLE-config.py as config.py) - LINUX
      run: python .github/workflows/verify_result.py -c false
    - if: ${{ matrix.os == 'windows-latest' && success() }}
      name: Setup config (using SAMPLE-config.py as config.py) - WINDOWS
      run: python .github\workflows\verify_result.py -c false
    - if: ${{ matrix.os == 'ubuntu-latest' && success() }} }}
      name: RUNNING TEST - LINUX
      run: |
         python default.py -t ${{TEST_TO_RUN}} -r -u https://webperf.se/ -o .github/workflows/testresult-${{TEST_TO_RUN}}.json
         python .github/workflows/verify_result.py -t ${{TEST_TO_RUN}}
    - if: ${{ matrix.os == 'windows-latest' && success() }}
      name: RUNNING TEST - WINDOWS
      run: |
         python default.py -t ${{TEST_TO_RUN}} -r -u https://webperf.se/ -o .github\workflows\testresult-${{TEST_TO_RUN}}.json
         python .github\workflows\verify_result.py -t ${{TEST_TO_RUN}}
