name: "Regression Test - Docker Image"
on:
  workflow_dispatch:
  push:
    paths:
      - '**regression-test-docker-image.yml'
      - 'software-full.json'
      - 'software-sources.json'
      - 'package.json'
      - 'update_software.py'
      - 'SAMPLE-software-rules.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t "webperf-runner:latest" .
