name: "Regression Test - Email (Beta) Test"
on: 
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      if: ${{ success() }}
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
      if: ${{ success() }}
    - name: Download IP2LOCATION DB (Using repository secret)
      shell: bash
      env:
        IP2LOCATION_DOWNLOAD_URL: ${{ secrets.IP2LOCATION_DOWNLOAD_URL }}
      run: wget -q -O - $IP2LOCATION_DOWNLOAD_URL | tar -xvzf - -C data
      if: ${{ success() }}
    - name: Test Tracking and Privacy - USE DOCKER
      run: |
        python .github/workflows/verify_result.py -c true
        python default.py -t 24 -r -u https://webperf.se/ -o .github/workflows/testresult-24.json
        python .github/workflows/verify_result.py -t 24
      if: ${{ success() }}
    - name: Test Tracking and Privacy - USE NPM PACKAGE
      run: |
        python .github/workflows/verify_result.py -c false
        python default.py -t 24 -r -u https://webperf.se/ -o .github/workflows/testresult-24.json
        python .github/workflows/verify_result.py -t 24
      if: ${{ success() }}